remote_theme: konstantin-morenko/just-the-docs

title: Как написать книгу 12+
description: |

  Трудно ли написать книгу?  Что нужно сделать для этого?  Какие
  задачи важны, а какие могут и подождать?

aux_links:
  "Купить книгу":
    - "https://konstantin-morenko.ru/howto-write-book/"
  "Другие книги":
    - "https://konstantin-morenko.ru/#books"
  "Константин Моренко":
    - "https://konstantin-morenko.ru"

ycnumber: 69954367
# mathjax: true
title_font_size: 18px
